// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAiLKwj7SXfnRI0n_3YUh7psY3V5L7jk5o',
//     appId: '1:1173067101:web:8da4eab2e5873286d7c4b4',
//     messagingSenderId: '1173067101',
//     projectId: 'supply-chain-409306',
//     authDomain: 'supply-chain-409306.firebaseapp.com',
//     storageBucket: 'supply-chain-409306.appspot.com',
//     measurementId: 'G-55884PCJK2',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBjgPKfdaQKEZzRDQhdZ82pzjJlLuEGS3U',
//     appId: '1:1173067101:android:2cbd9639bec52737d7c4b4',
//     messagingSenderId: '1173067101',
//     projectId: 'supply-chain-409306',
//     storageBucket: 'supply-chain-409306.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBnC-4yQIkqTgwKD61_2pp1IZJoU1snKFo',
//     appId: '1:1173067101:ios:f55d15ad2351cd91d7c4b4',
//     messagingSenderId: '1173067101',
//     projectId: 'supply-chain-409306',
//     storageBucket: 'supply-chain-409306.appspot.com',
//     iosBundleId: 'com.example.geminiClone',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBnC-4yQIkqTgwKD61_2pp1IZJoU1snKFo',
//     appId: '1:1173067101:ios:872293a7724d2650d7c4b4',
//     messagingSenderId: '1173067101',
//     projectId: 'supply-chain-409306',
//     storageBucket: 'supply-chain-409306.appspot.com',
//     iosBundleId: 'com.example.geminiClone.RunnerTests',
//   );
// }
